export const data = [
  {
    name: "John Deo ",
    gender: "male",
    avatar:
      "https://www.einfosoft.com/templates/admin/spiceangular/source/light/assets/images/user/user1.jpg",
    mobile: "1234567890 ",
    email: " test@email.com ",
    arrive: " 02/25/2018",
    depart: " 02/28/2018",
    roomType: " Delux",
    payment: "Paid",
    id: 1,
  },
  {
    name: "Sarah Smith ",
    avatar:
      "https://www.einfosoft.com/templates/admin/spiceangular/source/light/assets/images/user/user2.jpg",
    gender: "female",
    mobile: "1234567890 ",
    email: " test@email.com ",
    arrive: " 02/12/2018",
    depart: " 02/15/2018",
    roomType: " Super Delux",
    payment: "Unpaid",
    id: 2,
  },
  {
    name: "John Deo ",
    avatar:
      "https://www.einfosoft.com/templates/admin/spiceangular/source/light/assets/images/user/user3.jpg",
    gender: "male",
    mobile: "1234567890 ",
    email: " test@email.com ",
    arrive: " 02/25/2018",
    depart: " 02/18/2018",
    roomType: " Super Delux",
    payment: "Paid",
    id: 3,
  },
  {
    name: "Jay Soni ",
    avatar:
      "https://www.einfosoft.com/templates/admin/spiceangular/source/light/assets/images/user/user4.jpg",
    gender: "female",
    mobile: "1234567890 ",
    email: " test@email.com ",
    arrive: " 02/21/2018",
    depart: " 02/25/2018",
    roomType: " Delux",
    payment: "Paid",
    id: 4,
  },
  {
    name: "Smita Parikh ",
    avatar:
      "https://www.einfosoft.com/templates/admin/spiceangular/source/light/assets/images/user/user5.jpg",
    gender: "male",
    mobile: "1234567890 ",
    email: " test@email.com ",
    arrive: " 02/16/2018",
    depart: " 02/20/2018",
    roomType: " Vila",
    payment: "Unpaid",
    id: 5,
  },
  {
    name: "Pankaj Sinha ",
    avatar:
      "https://www.einfosoft.com/templates/admin/spiceangular/source/light/assets/images/user/user6.jpg",
    gender: "male",
    mobile: "1234567890 ",
    email: " test@email.com ",
    arrive: " 02/11/2018",
    depart: " 02/15/2018",
    roomType: " Double",
    payment: "Unpaid",
    id: 6,
  },
  {
    name: "Pankaj Sinha ",
    avatar:
      "https://www.einfosoft.com/templates/admin/spiceangular/source/light/assets/images/user/user7.jpg",
    gender: "male",
    mobile: "1234567890 ",
    email: " test@email.com ",
    arrive: " 02/27/2018",
    depart: " 02/28/2018",
    roomType: " Single",
    payment: "Unpaid",
    id: 7,
  },
  {
    name: "Jay Soni ",
    avatar:
      "https://www.einfosoft.com/templates/admin/spiceangular/source/light/assets/images/user/user8.jpg",
    gender: "female",
    mobile: "1234567890 ",
    email: " test@email.com ",
    arrive: " 02/17/2018",
    depart: " 02/20/2018",
    roomType: " Delux",
    payment: "Paid",
    id: 8,
  },
  {
    name: "Smita Parikh ",
    avatar:
      "https://www.einfosoft.com/templates/admin/spiceangular/source/light/assets/images/user/user9.jpg",
    gender: "female",
    mobile: "1234567890 ",
    email: " test@email.com ",
    arrive: " 02/07/2018",
    depart: " 02/10/2018",
    roomType: " Delux",
    payment: "Paid",
    id: 9,
  },
  {
    name: "Pooja Patel ",
    avatar:
      "https://www.einfosoft.com/templates/admin/spiceangular/source/light/assets/images/user/user10.jpg",
    gender: "male",
    mobile: "1234567890 ",
    email: " test@email.com ",
    arrive: " 02/09/2018",
    depart: " 02/15/2018",
    roomType: " Super Delux",
    payment: "Unpaid",
    id: 10,
  },
  {
    name: "Jay Soni ",
    avatar:
      "https://www.einfosoft.com/templates/admin/spiceangular/source/light/assets/images/user/user1.jpg",
    gender: "female",
    mobile: "1234567890 ",
    email: " test@email.com ",
    arrive: " 02/12/2018",
    depart: " 02/15/2018",
    roomType: " Super Delux",
    payment: "Unpaid",
    id: 11,
  },
  {
    name: "Pooja Patel ",
    avatar:
      "https://www.einfosoft.com/templates/admin/spiceangular/source/light/assets/images/user/user1.jpg",
    gender: "male",
    mobile: "1234567890 ",
    email: " test@email.com ",
    arrive: " 02/14/2018",
    depart: " 02/18/2018",
    roomType: " Delux",
    payment: "Paid",
    id: 12,
  },
  {
    name: "Sarah Smith ",
    avatar:
      "https://www.einfosoft.com/templates/admin/spiceangular/source/light/assets/images/user/user2.jpg",
    gender: "female",
    mobile: "1234567890 ",
    email: " test@email.com ",
    arrive: " 02/21/2018",
    depart: " 02/25/2018",
    roomType: " Delux",
    payment: "Unpaid",
    id: 13,
  },
  {
    name: "Smita Parikh ",
    avatar:
      "https://www.einfosoft.com/templates/admin/spiceangular/source/light/assets/images/user/user3.jpg",
    gender: "male",
    mobile: "1234567890 ",
    email: " test@email.com ",
    arrive: " 02/19/2018",
    depart: " 02/22/2018",
    roomType: " Vila",
    payment: "Paid",
    id: 14,
  },
  {
    name: "Jay Soni ",
    avatar:
      "https://www.einfosoft.com/templates/admin/spiceangular/source/light/assets/images/user/user4.jpg",
    gender: "female",
    mobile: "1234567890 ",
    email: " test@email.com ",
    arrive: " 02/20/2018",
    depart: " 02/21/2018",
    roomType: " Single",
    payment: "Unpaid",
    id: 15,
  },
  {
    name: "Pankaj Sinha ",
    avatar:
      "https://www.einfosoft.com/templates/admin/spiceangular/source/light/assets/images/user/user5.jpg",
    gender: "male",
    mobile: "1234567890 ",
    email: " test@email.com ",
    arrive: " 02/11/2018",
    depart: " 02/16/2018",
    roomType: " Super Delux",
    payment: "Paid",
    id: 16,
  },
];
