export const menuListData = [
  {
    name: "Mozzarella Dippers",
    price: "27",
    description: "Fried mozzarella sticks, marinara sauce",
    category: "Starters",
    id: 1,
  },
  {
    name: "Buffalo Wings",
    price: "37",
    description: "Spicy chicken wings, blue cheese sauce, carrot, celery",
    category: "Starters",
    id: 2,
  },
  {
    name: "Onion Rings",
    price: "32",
    description: "Fried onion rings, smoked aioli",
    category: "Starters",
    id: 3,
  },
  {
    name: "Chilli Con Carne",
    price: "32",
    description: "Spicy ground beef, bacon, kidney beans",
    category: "Starters",
    id: 4,
  },
  {
    name: "Fried Jalapeno",
    price: "52",
    description: "Fried jalapeno pickles, cheddar sauce",
    category: "Starters",
    id: 5,
  },
  {
    name: "Potato Skins",
    price: "42",
    description: "Crispy potato skins; bacon & cheddar or vegetables",
    category: "Starters",
    id: 6,
  },
  {
    name: "Rusty’s Burger",
    price: "27",
    description: "Smoked pulled beef ribs, bbq sauce, cheddar, crispy onion",
    category: "Mains",
    id: 7,
  },
  {
    name: "Crab Cake",
    price: "37",
    description: "Breaded crab cakes, tartar sauce, apple and fennel salad",
    category: "Mains",
    id: 8,
  },
  {
    name: "Cajun Fish Steak",
    price: "32",
    description: "Cajun spicied seabass, deep fried baby potatoes, side salad",
    category: "Mains",
    id: 9,
  },
  {
    name: "Baby Back Ribs",
    price: "32",
    description: "Bbq glazed baby pork ribs, coleslaw, fries",
    category: "Mains",
    id: 10,
  },
  {
    name: "Southern Fried Chicken",
    price: "52",
    description: "Cajun coated chicken breast, fries and honey mustard",
    category: "Mains",
    id: 11,
  },
  {
    name: "Smokehouse Combo",
    price: "42",
    description: "Smoked beef brisket, rib and sausage, coleslaw, cornbread",
    category: "Mains",
    id: 12,
  },
  {
    name: "Ceaser Salad",
    price: "47",
    description: "Romaine lettuce, croutons, parmigiano, Ceaser dressing.",
    category: "Salads",
    id: 13,
  },
  {
    name: "Grilled Salmon Salad",
    price: "37",
    description: "Grilled salmon, mixed greens, capers, orange slices",
    category: "Salads",
    id: 14,
  },
  {
    name: "Waldorf Salad",
    price: "52",
    description: "Lettuce, celery, apple, grape, walnut, waldorf sauce",
    category: "Salads",
    id: 15,
  },
  {
    name: "Chicken Cobb Salad",
    price: "32",
    description:
      "Iceberg lettuce, cherry tomatoes, blue cheese, avocado, bacon",
    category: "Salads",
    id: 16,
  },
  {
    name: "Quinoa & Avocado Salad",
    price: "52",
    description: "Quinoa, avocado, mixed greens. Nuts, dried and fresh fruits",
    category: "Salads",
    id: 17,
  },
  {
    name: "Salad Chicken",
    price: "42",
    description: "Ceaser dressing. Optional grilled chicken breast",
    category: "Salads",
    id: 18,
  },
  {
    name: "Château d'Yquem 2011",
    price: "400",
    description: "Dessert Wine, Bordeaux, Graves, Sauternes",
    category: "Wine",
    id: 19,
  },
  {
    name: "La Grande Année 2007",
    price: "400",
    description: "Rosé, Champagne",
    category: "Wine",
    id: 20,
  },
  {
    name: "Alvear Cream NV",
    price: "30",
    description: "Dessert, Fortified Wine, Andalucia",
    category: "Wine",
    id: 21,
  },
  {
    name: "Sine Qua Non 2012",
    price: "520",
    description: "Syrah, Shiraz & Blends, California",
    category: "Wine",
    id: 22,
  },
  {
    name: "Chateau D'yquem 1990",
    price: "900",
    description: "Dessert Wine, Bordeaux, Graves, Sauternes",
    category: "Wine",
    id: 23,
  },
  {
    name: "W.S. Keyes Winery 2006",
    price: "240",
    description: "Merlot, California, Napa, Howell Mountain",
    category: "Wine",
    id: 24,
  },
  {
    name: "Egg Benedict",
    price: "60",
    description: "English muffin, beef, hollandaise sauce, poached egg.",
    category: "Breakfast",
    id: 25,
  },
  {
    name: "Salmon Bagel",
    price: "30",
    description: "Smoked salmon, cream cheese, dill, rocket, red onion.",
    category: "Breakfast",
    id: 26,
  },
  {
    name: "Texas Benedict",
    price: "30",
    description: "English muffin, short ribs, bbq sauce, poached egg.",
    category: "Breakfast",
    id: 27,
  },
  {
    name: "Breakfast Bagel",
    price: "33",
    description: "Chocolate, marshmallow, biscuit bar",
    category: "Breakfast",
    id: 28,
  },
  {
    name: "Rusty’s Omlette",
    price: "22",
    description: "Mozzarella, cheddar, caramelized onion, black beans.",
    category: "Breakfast",
    id: 29,
  },
  {
    name: "Rusty’s Pancake",
    price: "40",
    description: "Strawberry, white chocolate, dark chocolate, crispearls",
    category: "Breakfast",
    id: 30,
  },
  {
    name: "Bourbon Pecan Pie",
    price: "67",
    description: "Bourbon pecan stuffed pie, vanilla ice-cream",
    category: "Dessert",
    id: 31,
  },
  {
    name: "S’mores",
    price: "40",
    description: "Chocolate chip cookies, marshmallow, chocolate",
    category: "Dessert",
    id: 32,
  },
  {
    name: "New York Cheesecake",
    price: "50",
    description: "Cheesecake, strawberry & lime salad",
    category: "Dessert",
    id: 33,
  },
  {
    name: "Rocky Road",
    price: "42",
    description: "Chocolate, marshmallow, biscuit bar",
    category: "Dessert",
    id: 34,
  },
  {
    name: "Rusty’s ice-cream",
    price: "32",
    description: "Vanilla, bourbon, cookie, chocolate ice-cream",
    category: "Dessert",
    id: 35,
  },
  {
    name: "Apple & Pear Crumble",
    price: "42",
    description: "Caramelized pear and apple, oat crumble, vanilla ice-cream",
    category: "Dessert",
    id: 36,
  },
];
export const menuTabs = [
  { name: "Starters" },
  { name: "Mains" },
  { name: "Salads" },
  { name: "Wine" },
  { name: "Breakfast" },
  { name: "Dessert" },
];
export const menuHeads = [
  {
    name: "Name",
    sortType: "name",
  },
  {
    name: "Description",
    sortType: "description",
  },
  {
    name: "Price",
    sortType: "price",
  },
    {
    name: "Action",
    sortType: null,
  },
];
