export const data = [
  {
    avatar: "https://i.postimg.cc/X7qnVJx5/download-1.jpg",
    name: "Cahyadi Purnomo",
    guestId: "#EMP-00025",
    dateOrder: "Oct 30th 2022 09:21 AM",
    checkIn: "Nov 2th, 2022 | 9.46 PM",
    checkOut: "Nov 2th, 2022 | 6.12 PM",
    specialRequest: "View Notes",
    roomType: "Deluxe A - 02",
    status: "Refund",
  },
  {
    avatar: "https://i.postimg.cc/q7sTmCBP/download-2.jpg",
    name: "Cahyadi Purnomo",
    guestId: "#EMP-00025",
    dateOrder: "Oct 30th 2022 09:21 AM",
    checkIn: "Nov 2th, 2022 | 9.46 PM",
    checkOut: "Nov 2th, 2022 | 6.12 PM",
    specialRequest: "View Notes",
    roomType: "Deluxe A - 02",
    status: "Pending",
  },
  {
    avatar: "https://i.postimg.cc/D0Z3yjQh/download-3.jpg",
    name: "Angela Smith",
    guestId: "#EMP-00025",
    dateOrder: "Oct 30th 2022 09:21 AM",
    checkIn: "Nov 2th, 2022 | 9.46 PM",
    checkOut: "Nov 2th, 2022 | 6.12 PM",
    specialRequest: "View Notes",
    roomType: "Deluxe A - 02",
    status: "Refund",
  },
  {
    avatar: "https://i.postimg.cc/8P7g2YPB/download-4.jpg",
    name: "Hendric Suratman",
    guestId: "#EMP-00025",
    dateOrder: "Oct 30th 2022 09:21 AM",
    checkIn: "Nov 2th, 2022 | 9.46 PM",
    checkOut: "Nov 2th, 2022 | 6.12 PM",
    specialRequest: "View Notes",
    roomType: "Deluxe A - 02",
    status: "Refund",
  },
  {
    avatar: "https://i.postimg.cc/50sDGBhR/download-5.jpg",
    name: "Jajang Lawrence",
    guestId: "#EMP-00025",
    dateOrder: "Oct 30th 2022 09:21 AM",
    checkIn: "Nov 2th, 2022 | 9.46 PM",
    checkOut: "Nov 2th, 2022 | 6.12 PM",
    specialRequest: "View Notes",
    roomType: "Deluxe A - 02",
    status: "Booked",
  },
  {
    avatar: "https://i.postimg.cc/xjFW3Pyk/download-6.jpg",
    name: "Kevin Stuart",
    guestId: "#EMP-00025",
    dateOrder: "Oct 30th 2022 09:21 AM",
    checkIn: "Nov 2th, 2022 | 9.46 PM",
    checkOut: "Nov 2th, 2022 | 6.12 PM",
    specialRequest: "View Notes",
    roomType: "Deluxe A - 02",
    status: "Refund",
  },
  {
    avatar: "https://i.postimg.cc/D0Z3yjQh/download-3.jpg",
    name: "Steven",
    guestId: "#EMP-00025",
    dateOrder: "Oct 30th 2022 09:21 AM",
    checkIn: "Nov 2th, 2022 | 9.46 PM",
    checkOut: "Nov 2th, 2022 | 6.12 PM",
    specialRequest: "View Notes",
    roomType: "Deluxe A - 02",
    status: "Pending",
  },
  {
    avatar: "https://i.postimg.cc/50sDGBhR/download-5.jpg",
    name: "Samantha",
    guestId: "#EMP-00025",
    dateOrder: "Oct 30th 2022 09:21 AM",
    checkIn: "Nov 2th, 2022 | 9.46 PM",
    checkOut: "Nov 2th, 2022 | 6.12 PM",
    specialRequest: "View Notes",
    roomType: "Deluxe A - 02",
    status: "Canceled",
  },
  {
    avatar: "https://i.postimg.cc/D0Z3yjQh/download-3.jpg",
    name: "Steven",
    guestId: "#EMP-00025",
    dateOrder: "Oct 30th 2022 09:21 AM",
    checkIn: "Nov 2th, 2022 | 9.46 PM",
    checkOut: "Nov 2th, 2022 | 6.12 PM",
    specialRequest: "View Notes",
    roomType: "Deluxe A - 02",
    status: "Pending",
  },
  {
    avatar: "https://i.postimg.cc/D0Z3yjQh/download-3.jpg",
    name: "Steven",
    guestId: "#EMP-00025",
    dateOrder: "Oct 30th 2022 09:21 AM",
    checkIn: "Nov 2th, 2022 | 9.46 PM",
    checkOut: "Nov 2th, 2022 | 6.12 PM",
    specialRequest: "View Notes",
    roomType: "Deluxe A - 02",
    status: "Pending",
  },
  {
    avatar: "https://i.postimg.cc/50sDGBhR/download-5.jpg",
    name: "Jajang Lawrence",
    guestId: "#EMP-00025",
    dateOrder: "Oct 30th 2022 09:21 AM",
    checkIn: "Nov 2th, 2022 | 9.46 PM",
    checkOut: "Nov 2th, 2022 | 6.12 PM",
    specialRequest: "View Notes",
    roomType: "Deluxe A - 02",
    status: "Booked",
  },
  {
    avatar: "https://i.postimg.cc/50sDGBhR/download-5.jpg",
    name: "Samantha",
    guestId: "#EMP-00025",
    dateOrder: "Oct 30th 2022 09:21 AM",
    checkIn: "Nov 2th, 2022 | 9.46 PM",
    checkOut: "Nov 2th, 2022 | 6.12 PM",
    specialRequest: "View Notes",
    roomType: "Deluxe A - 02",
    status: "Canceled",
  },
  {
    avatar: "https://i.postimg.cc/X7qnVJx5/download-1.jpg",
    name: "Cahyadi Purnomo",
    guestId: "#EMP-00025",
    dateOrder: "Oct 30th 2022 09:21 AM",
    checkIn: "Nov 2th, 2022 | 9.46 PM",
    checkOut: "Nov 2th, 2022 | 6.12 PM",
    specialRequest: "View Notes",
    roomType: "Deluxe A - 02",
    status: "Refund",
  },
  {
    avatar: "https://i.postimg.cc/D0Z3yjQh/download-3.jpg",
    name: "Angela Smith",
    guestId: "#EMP-00025",
    dateOrder: "Oct 30th 2022 09:21 AM",
    checkIn: "Nov 2th, 2022 | 9.46 PM",
    checkOut: "Nov 2th, 2022 | 6.12 PM",
    specialRequest: "View Notes",
    roomType: "Deluxe A - 02",
    status: "Refund",
  },
  {
    avatar: "https://i.postimg.cc/8P7g2YPB/download-4.jpg",
    name: "Hendric Suratman",
    guestId: "#EMP-00025",
    dateOrder: "Oct 30th 2022 09:21 AM",
    checkIn: "Nov 2th, 2022 | 9.46 PM",
    checkOut: "Nov 2th, 2022 | 6.12 PM",
    specialRequest: "View Notes",
    roomType: "Deluxe A - 02",
    status: "Refund",
  },
  {
    avatar: "https://i.postimg.cc/xjFW3Pyk/download-6.jpg",
    name: "Kevin Stuart",
    guestId: "#EMP-00025",
    dateOrder: "Oct 30th 2022 09:21 AM",
    checkIn: "Nov 2th, 2022 | 9.46 PM",
    checkOut: "Nov 2th, 2022 | 6.12 PM",
    specialRequest: "View Notes",
    roomType: "Deluxe A - 02",
    status: "Refund",
  },
];

export const guestListHeads = [
  {
    name: "Guest Name",
    sortType: "name",
  },
  {
    name: "Guest Id",
    sortType: "guestId",
  },
  {
    name: "Order Date",
    sortType: "dateOrder",
  },
  {
    name: "Check In",
    sortType: "checkIn",
  },
  {
    name: "Check Out",
    sortType: "checkOur",
  },
  {
    name: "Special Request",
    sortType: "specialRequest",
  },
  {
    name: "Room Type",
    sortType: "roomType",
  },
  {
    name: "Status",
    sortType: "status",
  },
  {
    name: "",
    sortType: "",
  },
];
